# sets parser options.
parser:
  # enables type inference for schemas. Schema parser will try to detect schema type by its properties.
  infer_types: true
  #  enables remote references resolving. See https://github.com/ogen-go/ogen/issues/385.
  allow_remote: true
  # is maximum depth of schema generation. Default is 1000.
  depth_limit: 1000
# sets generator options.
generator:
  convenient_errors: "auto"
  # sets generator features.
  features:
    enable:
      # Enables paths client generation
      - "paths/client"
      # Enables paths server generation
      - "paths/server"
      # Enables webhooks client generation
      # - 'webhooks/client'
      # Enables webhooks server generation
      # - 'webhooks/server'
      # Enables client usage in security source implementations
      - "client/security/reentrant"
      # Enables validation of client requests
      - "client/request/validation"
      # Enables validation of server responses
      - "server/response/validation"
      # Enables stub Handler generation
      - "ogen/unimplemented"
      # Enables example tests generation
      - "debug/example_tests"
      # Enables OpenTelemetry integration
      - "ogen/otel"
    # functions to ignore
    # ignore_not_implemented: ["all"]
# is a path to expanded spec.
expand: ""
