openapi: 3.0.3
info:
  title: GCS File Upload Service
  version: 1.0.0
  description: |
    Secure API for uploading spreadsheet files to Google Cloud Storage with Basic Authentication.
    Supports CSV and XLSX file formats with validation.
  contact:
    name: API Support
    email: support@example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:8080
    description: Development server
  - url: https://api.example.com
    description: Production server
paths:
  /upload:
    post:
      tags:
        - File Operations
      summary: Upload a spreadsheet file to Google Cloud Storage
      description: |
        Uploads a spreadsheet file to GCS bucket with the following constraints:
        - Maximum file size: 10MB
        - Allowed content types: 
          - CSV (text/csv, application/csv)
          - XLSX (application/vnd.openxmlformats-officedocument.spreadsheetml.sheet)
      operationId: uploadFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
                  description: Spreadsheet file to upload (CSV or XLSX)
                  x-content-type:
                    - text/csv
                    - application/csv
                    - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
      responses:
        "200":
          description: File uploaded successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadResponse"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
        "400":
          description: |
            Bad Request. Possible reasons:
            - Invalid file format (not CSV/XLSX)
            - File size exceeds 10MB limit
            - Missing file in request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: |
            Unauthorized. Valid reasons:
            - Missing Authorization header
            - Invalid credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: |
            Unexpected error response. Covers all status codes not explicitly defined.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: "*"
      security:
        - basicAuth: []
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: |
        Requires valid username/password combination.
        Credentials must be base64 encoded in the Authorization header.
  schemas:
    UploadResponse:
      type: object
      properties:
        filename:
          type: string
          description: Name of the uploaded file
        fileSize:
          type: integer
          format: int64
          description: Size of the uploaded file in bytes
        bucket:
          type: string
          description: GCS bucket where the file was stored
        gcspath:
          type: string
          format: string
          description: GCS Path
        uploadTime:
          type: string
          format: date-time
          description: Timestamp when the file was uploaded
      required:
        - filename
        - fileSize
        - bucket
        - gcs
        - uploadTime
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: HTTP status code
        message:
          type: string
          description: Error message
        details:
          type: array
          items:
            type: string
          description: Additional error details if available
      required:
        - code
        - message
