version: "3"
vars:
  API_SPEC: ./spec.yaml
  API_OUT_DIR: ./internal/fileupload
  GO_MODULE: http-file-upload
tasks:
  install-deps:
    desc: Install required dependencies
    cmds:
      - go install github.com/ogen-go/ogen/cmd/ogen@latest
      - go install github.com/go-task/task/v3/cmd/task@latest
  run:
    desc: Generate and re-build on changes
    cmds:
      - air
  hurl:
    desc: Hurl a test
    cmds:
      - hurl --test ./hurl/test.hurl
  generate:
    desc: Generate API client from OpenAPI spec
    cmds:
      - go generate ./...
  generate-watch:
    desc: Watch for changes in the API spec and regenerate
    cmds:
      - task: generate
      - watchexec -e yaml -w {{.API_SPEC}} "task generate"
  build:
    desc: Build the project
    deps: [generate]
    cmds:
      - go build ./...
  test:
    desc: Run tests
    deps: [generate]
    cmds:
      - go test ./...
  lint:
    desc: Run linters
    deps: [generate]
    cmds:
      - golangci-lint run ./...
  all:
    desc: Run all tasks
    deps: [generate, build, test, lint]
