POST http://localhost:8080/upload
[BasicAuth]
admin: $2y$10$qySn./7nLHtMNSFKfX08zOgWN0OzHWkfJJi9SZxdwDjH3qhG0VVkq
[MultipartFormData]
file: file,sample_data.csv;

# POST http://localhost:8080/upload
# [BasicAuth]
# admin: $2y$10$qySn./7nLHtMNSFKfX08zOgWN0OzHWkfJJi9SZxdwDjH3qhG0VVkq
# [MultipartFormData]
# file: file,sample_data.csv;type=text/csv

# POST http://localhost:8080/upload
# [BasicAuth]
# admin: $2y$10$qySn./7nLHtMNSFKfX08zOgWN0OzHWkfJJi9SZxdwDjH3qhG0VVkq
# [MultipartFormData]
# file: file,sample_data.xlsx;