// Code generated by ogen, DO NOT EDIT.

package fileupload

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// UploadFile implements uploadFile operation.
//
// Uploads a file to GCS bucket with the following constraints:
// - Maximum file size: 10MB
// - Allowed content types: text/plain, application/pdf, image/*.
//
// POST /upload
func (UnimplementedHandler) UploadFile(ctx context.Context, req *UploadFileReq) (r UploadFileRes, _ error) {
	return r, ht.ErrNotImplemented
}
